# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 841de383829562882f69e5221beaf6429c98f54559d6faa81ed51d3af3255c21ef4bf6e5eec748c052471b1e0dccd731355e925a278344e2a7de74756349803d

test:
  secret_key_base: 9aa03d58908bcc7951fcbee9ef82c099bd4a3cd1f07277075dc9a57e2847e01cdd3c3686829650f18fff3b1c21b8320ff19664f4a19fd28a6f06b0e7f502ba15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
